version: '3.9'

services:

  db: 
    image: postgres:16.1-alpine3.19
    restart: unless-stop
    env_file:
      - ./env_vars/.postgres_env
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"